theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
    math_engine: katex
    
#theme: minimal-mistakes-jekyll
#minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
